<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Store;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `BundleItem` schema in openapi.json. Do not edit by hand.
 */
final class BundleItemDTO extends Data
{
    public function __construct(
        public int $BasePrice,
        public string $CurrencyID,
        public float $DiscountPercent,
        public float $DiscountedPrice,
        public bool $IsPromoItem,
        public ItemDTO $Item,
    ) {}
}
