<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Store;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `Bundle` schema in openapi.json. Do not edit by hand.
 */
final class BundleDTO extends Data
{
    /**
     * @param  array<int, BundleItemDTO>  $Items
     */
    public function __construct(
        public string $CurrencyID,
        public string $DataAssetID,
        public int $DurationRemainingInSeconds,
        public string $ID,
        #[DataCollectionOf(BundleItemDTO::class)]
        public array $Items,
        public float $TotalDiscountPercent,
        public bool $WholesaleOnly,
    ) {}
}
