<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Store;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `FeaturedBundle` schema in openapi.json. Do not edit by hand.
 */
final class FeaturedBundleDTO extends Data
{
    /**
     * @param  array<int, BundleDTO>  $Bundles
     */
    public function __construct(
        public BundleDTO $Bundle,
        public int $BundleRemainingDurationInSeconds,
        #[DataCollectionOf(BundleDTO::class)]
        public array $Bundles,
    ) {}
}
