<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Store;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `Item` schema in openapi.json. Do not edit by hand.
 */
final class ItemDTO extends Data
{
    public function __construct(
        public int $Amount,
        public string $ItemID,
        public string $ItemTypeID,
    ) {}
}
