<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Store;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoreOffersV1UpgradeCurrency` schema in openapi.json. Do not edit by hand.
 */
final class StoreOffersUpgradeCurrencyDTO extends Data
{
    public function __construct(
        public float $DiscountedPercent,
        public StoreOffersOfferDTO $Offer,
        public string $OfferID,
        public string $StorefrontItemID,
    ) {}
}
