<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Store;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoreOffersV1Offer` schema in openapi.json. Do not edit by hand.
 */
final class StoreOffersOfferDTO extends Data
{
    /**
     * @param  array<string, int>  $Cost
     * @param  array<int, StoreOffersRewardDTO>  $Rewards
     */
    public function __construct(
        public array $Cost,
        public bool $IsDirectPurchase,
        public string $OfferID,
        #[DataCollectionOf(StoreOffersRewardDTO::class)]
        public array $Rewards,
        public string $StartDate,
    ) {}
}
