<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Store;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoreFeaturedV1` schema in openapi.json. Do not edit by hand.
 */
final class StoreFeaturedDTO extends Data
{
    public function __construct(
        public FeaturedBundleDTO $FeaturedBundle,
    ) {}
}
