<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Store;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoreOffersV1` schema in openapi.json. Do not edit by hand.
 */
final class StoreOffersDTO extends Data
{
    /**
     * @param  array<int, StoreOffersOfferDTO>  $Offers
     * @param  array<int, StoreOffersUpgradeCurrencyDTO>  $UpgradeCurrencyOffers
     */
    public function __construct(
        #[DataCollectionOf(StoreOffersOfferDTO::class)]
        public array $Offers,
        #[DataCollectionOf(StoreOffersUpgradeCurrencyDTO::class)]
        public array $UpgradeCurrencyOffers,
    ) {}
}
