<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Store;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoreOffersV1Reward` schema in openapi.json. Do not edit by hand.
 */
final class StoreOffersRewardDTO extends Data
{
    public function __construct(
        public string $ItemID,
        public string $ItemTypeID,
        public int $Quantity,
    ) {}
}
