<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premier;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremierTeamV1ResponseDataStats` schema in openapi.json. Do not edit by hand.
 */
final class PremierTeamResponseDataStatsDTO extends Data
{
    public function __construct(
        public int $losses,
        public int $matches,
        public int $rounds_lost,
        public int $rounds_won,
        public int $wins,
    ) {}
}
