<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premier;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremierTeamV1ResponseData` schema in openapi.json. Do not edit by hand.
 */
final class PremierTeamResponseDataDTO extends Data
{
    /**
     * @param  array<int, PremierTeamMemberDTO>  $member
     */
    public function __construct(
        public PremierTeamResponseDataCustomizationDTO $customization,
        public bool $enrolled,
        public string $id,
        #[DataCollectionOf(PremierTeamMemberDTO::class)]
        public array $member,
        public string $name,
        public PremierTeamResponseDataPlacementDTO $placement,
        public bool $ranked,
        public PremierTeamResponseDataStatsDTO $stats,
        public string $tag,
    ) {}
}
