<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premier;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremierTeamGamesLeagueString` schema in openapi.json. Do not edit by hand.
 */
final class PremierTeamGamesLeagueStringDTO extends Data
{
    public function __construct(
        public string $id,
        public int $points_after,
        public int $points_before,
        public string $started_at,
    ) {}
}
