<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premier;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremierTeamV1ResponseDataCustomization` schema in openapi.json. Do not edit by hand.
 */
final class PremierTeamResponseDataCustomizationDTO extends Data
{
    public function __construct(
        public string $icon,
        public string $image,
        public string $primary,
        public string $secondary,
        public string $tertiary,
    ) {}
}
