<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premier;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremierTeamMember` schema in openapi.json. Do not edit by hand.
 */
final class PremierTeamMemberDTO extends Data
{
    public function __construct(
        public string $puuid,
        public ?string $name = null,
        public ?string $tag = null,
    ) {}
}
