<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premier;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremierTeamV1ResponseDataPlacement` schema in openapi.json. Do not edit by hand.
 */
final class PremierTeamResponseDataPlacementDTO extends Data
{
    public function __construct(
        public string $conference,
        public int $division,
        public int $place,
        public int $points,
    ) {}
}
