<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premier;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremierTeamHistoryV1ResponseData` schema in openapi.json. Do not edit by hand.
 */
final class PremierTeamHistoryResponseDataDTO extends Data
{
    /**
     * @param  array<int, PremierTeamGamesLeagueStringDTO>  $league_matches
     * @param  array<int, PremierTeamGamesTournamentDTO>  $tournament_matches
     */
    public function __construct(
        #[DataCollectionOf(PremierTeamGamesLeagueStringDTO::class)]
        public array $league_matches,
        #[DataCollectionOf(PremierTeamGamesTournamentDTO::class)]
        public array $tournament_matches,
    ) {}
}
