<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premier;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremierTeamGamesTournament` schema in openapi.json. Do not edit by hand.
 */
final class PremierTeamGamesTournamentDTO extends Data
{
    /**
     * @param  array<int, string>  $matches
     */
    public function __construct(
        public array $matches,
        public int $placement,
        public int $placement_league_bonus,
        public int $points_after,
        public int $points_before,
        public string $tournament_id,
    ) {}
}
