<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premier;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremierTeamLiteResponseData` schema in openapi.json. Do not edit by hand.
 */
final class PremierTeamLiteResponseDataDTO extends Data
{
    public function __construct(
        public string $affinity,
        public string $conference,
        public PremierTeamResponseDataCustomizationDTO $customization,
        public int $division,
        public string $id,
        public int $losses,
        public string $name,
        public bool $ranked,
        public int $ranking,
        public string $region,
        public int $score,
        public string $tag,
        public string $updated_at,
        public int $wins,
    ) {}
}
