<?php

namespace Tobiasn\ValorantApi\Requests\Premium;

use Saloon\Contracts\Body\HasBody;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\Traits\Body\HasJsonBody;
use Tobiasn\ValorantApi\DataTransferObjects\Premium\PremiumWebhookUserAddRequestDTO;
use Tobiasn\ValorantApi\DataTransferObjects\Premium\PremiumWebhookUserMutationDataDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;
use Tobiasn\ValorantApi\Requests\Concerns\SendsJsonPayload;

/**
 * Add premium webhook user
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/premium
 *
 * @generated by bin/generate.php
 */
class AddWebhookUserRequest extends Request implements HasBody
{
    use HasJsonBody;
    use NormalisesParameters;
    use ReadsResponseData;
    use SendsJsonPayload;

    protected Method $method = Method::POST;

    /**
     * @param  PremiumWebhookUserAddRequestDTO  $payload  The request body sent as JSON.
     */
    public function __construct(
        private readonly PremiumWebhookUserAddRequestDTO $payload,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/public/v1/premium/webhook/users';
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultBody(): array
    {
        return $this->payloadToBody($this->payload);
    }

    public function createDtoFromResponse(Response $response): PremiumWebhookUserMutationDataDTO
    {
        return PremiumWebhookUserMutationDataDTO::from($this->data($response));
    }
}
