<?php

namespace Tobiasn\ValorantApi\Requests\Premium;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Premium\PremiumWebhookDeleteDataDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Delete premium webhook user
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/premium
 *
 * @generated by bin/generate.php
 */
class DeleteWebhookUserRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::DELETE;

    /**
     * @param  string  $id  Tracked user id
     */
    public function __construct(
        private readonly string $id,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/public/v1/premium/webhook/users/'.$this->segment($this->id);
    }

    public function createDtoFromResponse(Response $response): PremiumWebhookDeleteDataDTO
    {
        return PremiumWebhookDeleteDataDTO::from($this->data($response));
    }
}
