<?php

namespace Tobiasn\ValorantApi\Requests\Premium;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;

/**
 * Get premium webhook settings
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/premium
 *
 * @generated by bin/generate.php
 */
class GetWebhookSettingsRequest extends Request
{
    use NormalisesParameters;

    protected Method $method = Method::GET;

    public function resolveEndpoint(): string
    {
        return '/public/v1/premium/webhook';
    }
}
