<?php

namespace Tobiasn\ValorantApi\Requests\Premium;

use Saloon\Contracts\Body\HasBody;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Traits\Body\HasJsonBody;
use Tobiasn\ValorantApi\DataTransferObjects\Premium\PremiumWebhookUserUpdateRequestDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\SendsJsonPayload;

/**
 * Update premium webhook user
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/premium
 *
 * @generated by bin/generate.php
 */
class UpdateWebhookUserRequest extends Request implements HasBody
{
    use HasJsonBody;
    use NormalisesParameters;
    use SendsJsonPayload;

    protected Method $method = Method::PUT;

    /**
     * @param  string  $id  Tracked user id
     * @param  PremiumWebhookUserUpdateRequestDTO  $payload  The request body sent as JSON.
     */
    public function __construct(
        private readonly string $id,
        private readonly PremiumWebhookUserUpdateRequestDTO $payload,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/public/v1/premium/webhook/users/'.$this->segment($this->id);
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultBody(): array
    {
        return $this->payloadToBody($this->payload);
    }
}
