<?php

namespace Tobiasn\ValorantApi\Requests\Crosshair;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;

/**
 * Generate crosshair image (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/crosshair
 *
 * @generated by bin/generate.php
 */
class GenerateCrosshairRequest extends Request
{
    use NormalisesParameters;

    protected Method $method = Method::GET;

    /**
     * @param  string|null  $id  Crosshair code
     */
    public function __construct(
        private readonly ?string $id = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/crosshair/generate';
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'id' => $this->id,
        ]);
    }
}
