<?php

namespace Tobiasn\ValorantApi\Requests\Mmr;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Mmr\MMRHistoryDataDTO;
use Tobiasn\ValorantApi\Enums\Platform;
use Tobiasn\ValorantApi\Enums\Region;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get MMR history by PUUID (v2)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/mmr
 *
 * @generated by bin/generate.php
 */
class GetMmrHistoryByPuuidRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  Region|string  $affinity  Region/affinity (e.g., na, eu, ap, kr)
     * @param  Platform|string  $platform  Platform (pc, console)
     * @param  string  $puuid  Player UUID
     */
    public function __construct(
        private readonly Region|string $affinity,
        private readonly Platform|string $platform,
        private readonly string $puuid,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v2/by-puuid/mmr-history/'.$this->segment($this->affinity).'/'.$this->segment($this->platform).'/'.$this->segment($this->puuid);
    }

    public function createDtoFromResponse(Response $response): MMRHistoryDataDTO
    {
        return MMRHistoryDataDTO::from($this->data($response));
    }
}
