<?php

namespace Tobiasn\ValorantApi\Requests\Mmr;

use Illuminate\Support\Collection;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Stored\StoredMMRDTO;
use Tobiasn\ValorantApi\Enums\Platform;
use Tobiasn\ValorantApi\Enums\Region;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get stored MMR history by name (v2)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/mmr
 *
 * @generated by bin/generate.php
 */
class GetStoredMmrHistoryRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  Region|string  $affinity  Region/affinity (e.g., na, eu, ap, kr)
     * @param  Platform|string  $platform  Platform (pc, console)
     * @param  string  $name  Riot ID name
     * @param  string  $tag  Riot ID tag
     * @param  int|null  $size  Number of results (optional)
     */
    public function __construct(
        private readonly Region|string $affinity,
        private readonly Platform|string $platform,
        private readonly string $name,
        private readonly string $tag,
        private readonly ?int $size = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v2/stored-mmr-history/'.$this->segment($this->affinity).'/'.$this->segment($this->platform).'/'.$this->segment($this->name).'/'.$this->segment($this->tag);
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'size' => $this->size,
        ]);
    }

    /**
     * @return Collection<int, StoredMMRDTO>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        return collect($this->data($response))->map(static fn (mixed $item): StoredMMRDTO => StoredMMRDTO::from($item));
    }
}
