<?php

namespace Tobiasn\ValorantApi\Requests\Matches;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Matches\MatchesDataDTO;
use Tobiasn\ValorantApi\Enums\Region;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get match details (v4)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/matches
 *
 * @generated by bin/generate.php
 */
class GetMatchRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  Region|string  $affinity  Region/affinity (e.g., na, eu, ap, kr)
     * @param  string  $matchId  Match UUID
     */
    public function __construct(
        private readonly Region|string $affinity,
        private readonly string $matchId,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v4/match/'.$this->segment($this->affinity).'/'.$this->segment($this->matchId);
    }

    public function createDtoFromResponse(Response $response): MatchesDataDTO
    {
        return MatchesDataDTO::from($this->data($response));
    }
}
