<?php

namespace Tobiasn\ValorantApi\Requests\Matches;

use Illuminate\Support\Collection;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Matches\MatchesDataDTO;
use Tobiasn\ValorantApi\Enums\Platform;
use Tobiasn\ValorantApi\Enums\Region;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get matches by PUUID (v4)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/matches
 *
 * @generated by bin/generate.php
 */
class GetMatchesByPuuidRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  Region|string  $affinity  Region/affinity (e.g., na, eu, ap, kr)
     * @param  Platform|string  $platform  Platform (pc, console)
     * @param  string  $puuid  Player UUID
     * @param  string|null  $mode  Game mode filter (optional)
     * @param  string|null  $map  Map filter (optional)
     * @param  int|null  $size  Number of results (optional)
     * @param  int|null  $start  Start index for pagination (optional)
     */
    public function __construct(
        private readonly Region|string $affinity,
        private readonly Platform|string $platform,
        private readonly string $puuid,
        private readonly ?string $mode = null,
        private readonly ?string $map = null,
        private readonly ?int $size = null,
        private readonly ?int $start = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v4/by-puuid/matches/'.$this->segment($this->affinity).'/'.$this->segment($this->platform).'/'.$this->segment($this->puuid);
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'mode' => $this->mode,
            'map' => $this->map,
            'size' => $this->size,
            'start' => $this->start,
        ]);
    }

    /**
     * @return Collection<int, MatchesDataDTO>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        return collect($this->data($response))->map(static fn (mixed $item): MatchesDataDTO => MatchesDataDTO::from($item));
    }
}
