<?php

namespace Tobiasn\ValorantApi\Requests\Account;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Account\AccountDataDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get account by PUUID (v2)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/account
 *
 * @generated by bin/generate.php
 */
class GetAccountByPuuidRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  string  $puuid  Player UUID
     * @param  bool|null  $force  Bypass cache and refresh (optional)
     */
    public function __construct(
        private readonly string $puuid,
        private readonly ?bool $force = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v2/by-puuid/account/'.$this->segment($this->puuid);
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'force' => $this->force,
        ]);
    }

    public function createDtoFromResponse(Response $response): AccountDataDTO
    {
        return AccountDataDTO::from($this->data($response));
    }
}
