<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Mmr;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MMRV3Account` schema in openapi.json. Do not edit by hand.
 */
final class MMRAccountDTO extends Data
{
    public function __construct(
        public string $name,
        public string $puuid,
        public string $tag,
    ) {}
}
