<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Mmr;

use Spatie\LaravelData\Data;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\TierIdNameComboDTO;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MMRV3Current` schema in openapi.json. Do not edit by hand.
 */
final class MMRCurrentDTO extends Data
{
    public function __construct(
        public int $elo,
        public int $games_needed_for_rating,
        public int $last_change,
        public int $rank_protection_shields,
        public int $rr,
        public TierIdNameComboDTO $tier,
        public ?MMRLeaderboardPlacementDTO $leaderboard_placement = null,
    ) {}
}
