<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Mmr;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MMRV3Data` schema in openapi.json. Do not edit by hand.
 */
final class MMRDataDTO extends Data
{
    /**
     * @param  array<int, MMRSeasonalDTO>  $seasonal
     */
    public function __construct(
        public MMRAccountDTO $account,
        public MMRCurrentDTO $current,
        #[DataCollectionOf(MMRSeasonalDTO::class)]
        public array $seasonal,
        public ?MMRPeakDTO $peak = null,
    ) {}
}
