<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Mmr;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MMRHistoryV2Data` schema in openapi.json. Do not edit by hand.
 */
final class MMRHistoryDataDTO extends Data
{
    /**
     * @param  array<int, MMRHistoryHistoryDTO>  $history
     */
    public function __construct(
        public MMRAccountDTO $account,
        #[DataCollectionOf(MMRHistoryHistoryDTO::class)]
        public array $history,
    ) {}
}
