<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Mmr;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MMRV3LeaderboardPlacement` schema in openapi.json. Do not edit by hand.
 */
final class MMRLeaderboardPlacementDTO extends Data
{
    public function __construct(
        public int $rank,
        public string $updated_at,
    ) {}
}
