<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Mmr;

use Spatie\LaravelData\Data;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\SeasonIdShortComboDTO;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\TierIdNameComboDTO;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MMRV3Peak` schema in openapi.json. Do not edit by hand.
 */
final class MMRPeakDTO extends Data
{
    public function __construct(
        public string $ranking_schema,
        public int $rr,
        public SeasonIdShortComboDTO $season,
        public TierIdNameComboDTO $tier,
    ) {}
}
