<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Mmr;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\SeasonIdShortComboDTO;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\TierIdNameComboDTO;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MMRV3Seasonal` schema in openapi.json. Do not edit by hand.
 */
final class MMRSeasonalDTO extends Data
{
    /**
     * @param  array<int, TierIdNameComboDTO>  $act_wins
     */
    public function __construct(
        #[DataCollectionOf(TierIdNameComboDTO::class)]
        public array $act_wins,
        public int $end_rr,
        public TierIdNameComboDTO $end_tier,
        public int $games,
        public string $ranking_schema,
        public SeasonIdShortComboDTO $season,
        public int $wins,
        public ?MMRLeaderboardPlacementDTO $leaderboard_placement = null,
    ) {}
}
