<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Stored;

use Spatie\LaravelData\Data;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\MapIdNameComboDTO;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\SeasonIdShortComboDTO;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\TierIdNameComboDTO;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoredMMRV2` schema in openapi.json. Do not edit by hand.
 */
final class StoredMMRDTO extends Data
{
    public function __construct(
        public string $date,
        public int $elo,
        public int $last_change,
        public MapIdNameComboDTO $map,
        public string $match_id,
        public int $refunded_rr,
        public int $rr,
        public SeasonIdShortComboDTO $season,
        public TierIdNameComboDTO $tier,
        public bool $was_derank_protected,
    ) {}
}
