<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Stored;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoredMatchStatsDamage` schema in openapi.json. Do not edit by hand.
 */
final class StoredMatchStatsDamageDTO extends Data
{
    public function __construct(
        public int $made,
        public int $received,
    ) {}
}
