<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Stored;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoredMatchTeam` schema in openapi.json. Do not edit by hand.
 */
final class StoredMatchTeamDTO extends Data
{
    public function __construct(
        public int $blue,
        public int $red,
    ) {}
}
