<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Stored;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoredMatchMeta` schema in openapi.json. Do not edit by hand.
 */
final class StoredMatchMetaDTO extends Data
{
    public function __construct(
        public string $id,
        public StoredMatchMetaMapDTO $map,
        public string $mode,
        public string $region,
        public StoredMatchMetaSeasonDTO $season,
        public string $started_at,
        public string $version,
        public ?string $cluster = null,
    ) {}
}
