<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Stored;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoredMatch` schema in openapi.json. Do not edit by hand.
 */
final class StoredMatchDTO extends Data
{
    public function __construct(
        public StoredMatchMetaDTO $meta,
        public StoredMatchStatsDTO $stats,
        public StoredMatchTeamDTO $teams,
    ) {}
}
