<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Stored;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoredMatchStatsShots` schema in openapi.json. Do not edit by hand.
 */
final class StoredMatchStatsShotsDTO extends Data
{
    public function __construct(
        public int $body,
        public int $head,
        public int $leg,
    ) {}
}
