<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Stored;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StoredMatchStats` schema in openapi.json. Do not edit by hand.
 */
final class StoredMatchStatsDTO extends Data
{
    public function __construct(
        public int $assists,
        public StoredMatchStatsCharacterDTO $character,
        public StoredMatchStatsDamageDTO $damage,
        public int $deaths,
        public int $kills,
        public int $level,
        public string $puuid,
        public int $score,
        public StoredMatchStatsShotsDTO $shots,
        public string $team,
        public int $tier,
        public ?string $name = null,
        public ?string $tag = null,
    ) {}
}
