<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataObserver` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataObserverDTO extends Data
{
    public function __construct(
        public int $account_level,
        public string $card_id,
        public string $name,
        public string $party_id,
        public string $puuid,
        public int $session_playtime_in_ms,
        public string $tag,
        public string $title_id,
    ) {}
}
