<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRoundPlayerLocations` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundPlayerLocationsDTO extends Data
{
    public function __construct(
        public MatchesDataRoundLocationDTO $location,
        public MatchesDataRoundPlayerDTO $player,
        public float $view_radians,
    ) {}
}
