<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRoundPlayerStatsDamageEvents` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundPlayerStatsDamageEventsDTO extends Data
{
    public function __construct(
        public int $bodyshots,
        public int $damage,
        public int $headshots,
        public int $legshots,
        public MatchesDataRoundPlayerDTO $player,
    ) {}
}
