<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRoundPlayerStatsEconomy` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundPlayerStatsEconomyDTO extends Data
{
    public function __construct(
        public int $loadout_value,
        public int $remaining,
        public ?MatchesDataRoundPlayerStatsEconomyArmorDTO $armor = null,
        public ?MatchesDataRoundPlayerStatsEconomyWeaponDTO $weapon = null,
    ) {}
}
