<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataMetadataQueue` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataMetadataQueueDTO extends Data
{
    public function __construct(
        public string $id,
        public ?string $mode_type = null,
        public ?string $name = null,
    ) {}
}
