<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRoundPlayerStatsAbilityCasts` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundPlayerStatsAbilityCastsDTO extends Data
{
    public function __construct(
        public ?int $ability_1 = null,
        public ?int $ability_2 = null,
        public ?int $grenade = null,
        public ?int $ultimate = null,
    ) {}
}
