<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataPlayerBehaviorFriendlyFire` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataPlayerBehaviorFriendlyFireDTO extends Data
{
    public function __construct(
        public float $incoming,
        public float $outgoing,
    ) {}
}
