<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataPlayerStatsDamage` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataPlayerStatsDamageDTO extends Data
{
    public function __construct(
        public int $dealt,
        public int $received,
    ) {}
}
