<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataTeamPremierRoster` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataTeamPremierRosterDTO extends Data
{
    /**
     * @param  array<int, string>  $members
     */
    public function __construct(
        public MatchesDataTeamPremierRosterCustomizationDTO $customization,
        public string $id,
        public array $members,
        public string $name,
        public string $tag,
    ) {}
}
