<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataTeamPremierRosterCustomization` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataTeamPremierRosterCustomizationDTO extends Data
{
    public function __construct(
        public string $icon,
        public string $image,
        public string $primary_color,
        public string $secondary_color,
        public string $tertiary_color,
    ) {}
}
