<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\MapIdNameComboDTO;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\SeasonIdShortComboDTO;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataMetadata` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataMetadataDTO extends Data
{
    /**
     * @param  array<int, MatchesDataMetadataPartyRRPenaltyDTO>  $party_rr_penaltys
     */
    public function __construct(
        public int $game_length_in_ms,
        public string $game_version,
        public bool $is_completed,
        public MapIdNameComboDTO $map,
        public string $match_id,
        #[DataCollectionOf(MatchesDataMetadataPartyRRPenaltyDTO::class)]
        public array $party_rr_penaltys,
        public string $platform,
        public MatchesDataMetadataQueueDTO $queue,
        public SeasonIdShortComboDTO $season,
        public string $started_at,
        public ?string $cluster = null,
        public mixed $premier = null,
        public ?string $region = null,
    ) {}
}
