<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataPlayerStats` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataPlayerStatsDTO extends Data
{
    public function __construct(
        public int $assists,
        public int $bodyshots,
        public MatchesDataPlayerStatsDamageDTO $damage,
        public int $deaths,
        public int $headshots,
        public int $kills,
        public int $legshots,
        public int $score,
    ) {}
}
