<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataCoach` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataCoachDTO extends Data
{
    public function __construct(
        public string $puuid,
        public string $team_id,
    ) {}
}
