<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataTeamRounds` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataTeamRoundsDTO extends Data
{
    public function __construct(
        public int $lost,
        public int $won,
    ) {}
}
