<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataMetadataPartyRRPenalty` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataMetadataPartyRRPenaltyDTO extends Data
{
    public function __construct(
        public string $party_id,
        public float $penalty,
    ) {}
}
