<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRound` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundDTO extends Data
{
    /**
     * @param  array<int, MatchesDataRoundPlayerStatsDTO>  $stats
     */
    public function __construct(
        public string $ceremony,
        public int $id,
        public string $result,
        #[DataCollectionOf(MatchesDataRoundPlayerStatsDTO::class)]
        public array $stats,
        public string $winning_team,
        public ?MatchesDataRoundDefuseDTO $defuse = null,
        public ?MatchesDataRoundPlantDTO $plant = null,
    ) {}
}
