<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataPlayerEconomyLoadoutValue` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataPlayerEconomyLoadoutValueDTO extends Data
{
    public function __construct(
        public float $average,
        public int $overall,
    ) {}
}
