<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRoundLocation` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundLocationDTO extends Data
{
    public function __construct(
        public int $x,
        public int $y,
    ) {}
}
