<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataPlayerEconomy` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataPlayerEconomyDTO extends Data
{
    public function __construct(
        public MatchesDataPlayerEconomyLoadoutValueDTO $loadout_value,
        public MatchesDataPlayerEconomySpentDTO $spent,
    ) {}
}
