<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataTeam` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataTeamDTO extends Data
{
    public function __construct(
        public MatchesDataTeamRoundsDTO $rounds,
        public string $team_id,
        public bool $won,
        public ?MatchesDataTeamPremierRosterDTO $premier_roster = null,
    ) {}
}
