<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4Data` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataDTO extends Data
{
    /**
     * @param  array<int, MatchesDataCoachDTO>  $coaches
     * @param  array<int, MatchesDataKillDTO>  $kills
     * @param  array<int, MatchesDataObserverDTO>  $observers
     * @param  array<int, MatchesDataPlayerDTO>  $players
     * @param  array<int, MatchesDataRoundDTO>  $rounds
     * @param  array<int, MatchesDataTeamDTO>  $teams
     */
    public function __construct(
        #[DataCollectionOf(MatchesDataCoachDTO::class)]
        public array $coaches,
        #[DataCollectionOf(MatchesDataKillDTO::class)]
        public array $kills,
        public MatchesDataMetadataDTO $metadata,
        #[DataCollectionOf(MatchesDataObserverDTO::class)]
        public array $observers,
        #[DataCollectionOf(MatchesDataPlayerDTO::class)]
        public array $players,
        #[DataCollectionOf(MatchesDataRoundDTO::class)]
        public array $rounds,
        #[DataCollectionOf(MatchesDataTeamDTO::class)]
        public array $teams,
    ) {}
}
