<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRoundDefuse` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundDefuseDTO extends Data
{
    /**
     * @param  array<int, MatchesDataRoundPlayerLocationsDTO>  $player_locations
     */
    public function __construct(
        public MatchesDataRoundLocationDTO $location,
        public MatchesDataRoundPlayerDTO $player,
        #[DataCollectionOf(MatchesDataRoundPlayerLocationsDTO::class)]
        public array $player_locations,
        public int $round_time_in_ms,
    ) {}
}
