<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\AgentIdNameComboDTO;
use Tobiasn\ValorantApi\DataTransferObjects\Shared\TierIdNameComboDTO;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataPlayer` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataPlayerDTO extends Data
{
    public function __construct(
        public MatchesDataPlayerAbilityCastsDTO $ability_casts,
        public int $account_level,
        public AgentIdNameComboDTO $agent,
        public MatchesDataPlayerBehaviorDTO $behavior,
        public MatchesDataPlayerCustomizationDTO $customization,
        public MatchesDataPlayerEconomyDTO $economy,
        public string $name,
        public string $party_id,
        public string $platform,
        public string $puuid,
        public int $session_playtime_in_ms,
        public MatchesDataPlayerStatsDTO $stats,
        public string $tag,
        public string $team_id,
        public TierIdNameComboDTO $tier,
    ) {}
}
