<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRoundPlayer` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundPlayerDTO extends Data
{
    public function __construct(
        public string $name,
        public string $puuid,
        public string $tag,
        public string $team,
    ) {}
}
