<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataPlayerCustomization` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataPlayerCustomizationDTO extends Data
{
    public function __construct(
        public string $card,
        public string $title,
        public ?string $preferred_level_border = null,
    ) {}
}
