<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataKill` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataKillDTO extends Data
{
    /**
     * @param  array<int, MatchesDataRoundPlayerDTO>  $assistants
     * @param  array<int, MatchesDataRoundPlayerLocationsDTO>  $player_locations
     */
    public function __construct(
        #[DataCollectionOf(MatchesDataRoundPlayerDTO::class)]
        public array $assistants,
        public MatchesDataRoundPlayerDTO $killer,
        public MatchesDataRoundLocationDTO $location,
        #[DataCollectionOf(MatchesDataRoundPlayerLocationsDTO::class)]
        public array $player_locations,
        public int $round,
        public bool $secondary_fire_mode,
        public int $time_in_match_in_ms,
        public int $time_in_round_in_ms,
        public MatchesDataRoundPlayerDTO $victim,
        public MatchesDataRoundPlayerStatsEconomyWeaponDTO $weapon,
    ) {}
}
