<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRoundPlayerStatsEconomyWeapon` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundPlayerStatsEconomyWeaponDTO extends Data
{
    public function __construct(
        public ?string $id = null,
        public ?string $name = null,
        public ?string $type = null,
    ) {}
}
