<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRoundPlayerStats` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundPlayerStatsDTO extends Data
{
    /**
     * @param  array<int, MatchesDataRoundPlayerStatsDamageEventsDTO>  $damage_events
     */
    public function __construct(
        public MatchesDataRoundPlayerStatsAbilityCastsDTO $ability_casts,
        #[DataCollectionOf(MatchesDataRoundPlayerStatsDamageEventsDTO::class)]
        public array $damage_events,
        public MatchesDataRoundPlayerStatsEconomyDTO $economy,
        public MatchesDataRoundPlayerDTO $player,
        public bool $received_penalty,
        public MatchesDataRoundPlayerStatsStatsDTO $stats,
        public bool $stayed_in_spawn,
        public bool $was_afk,
    ) {}
}
