<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataPlayerBehavior` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataPlayerBehaviorDTO extends Data
{
    public function __construct(
        public float $afk_rounds,
        public MatchesDataPlayerBehaviorFriendlyFireDTO $friendly_fire,
        public float $rounds_in_spawn,
    ) {}
}
