<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Matches;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `MatchesV4DataRoundPlayerStatsStats` schema in openapi.json. Do not edit by hand.
 */
final class MatchesDataRoundPlayerStatsStatsDTO extends Data
{
    public function __construct(
        public int $bodyshots,
        public int $headshots,
        public int $kills,
        public int $legshots,
        public int $score,
    ) {}
}
