<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `QueueStatusV1Map` schema in openapi.json. Do not edit by hand.
 */
final class QueueStatusMapDTO extends Data
{
    public function __construct(
        public string $id,
        public string $name,
    ) {}
}
