<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `QueueStatusV1SkillDisparity` schema in openapi.json. Do not edit by hand.
 */
final class QueueStatusSkillDisparityDTO extends Data
{
    public function __construct(
        public QueueStatusIDNamePairDTO $max_tier,
        public string $name,
        public int $tier,
    ) {}
}
