<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `QueueStatusV1PartySize` schema in openapi.json. Do not edit by hand.
 */
final class QueueStatusPartySizeDTO extends Data
{
    /**
     * @param  array<int, int>  $invalid
     */
    public function __construct(
        public bool $full_party_bypass,
        public array $invalid,
        public int $max,
        public int $min,
    ) {}
}
