<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `QueueStatusV1IDNamePair` schema in openapi.json. Do not edit by hand.
 */
final class QueueStatusIDNamePairDTO extends Data
{
    public function __construct(
        public int $id,
        public string $name,
    ) {}
}
