<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `QueueStatusV1Data` schema in openapi.json. Do not edit by hand.
 */
final class QueueStatusDataDTO extends Data
{
    /**
     * @param  array<int, QueueStatusMapsDTO>  $maps
     * @param  array<int, string>  $platforms
     * @param  array<int, QueueStatusSkillDisparityDTO>  $skill_disparity
     */
    public function __construct(
        public bool $enabled,
        public QueueStatusGameRulesDTO $game_rules,
        public QueueStatusHighSkillDTO $high_skill,
        #[DataCollectionOf(QueueStatusMapsDTO::class)]
        public array $maps,
        public string $mode,
        public string $mode_id,
        public int $number_of_teams,
        public QueueStatusPartySizeDTO $party_size,
        public array $platforms,
        public bool $ranked,
        public int $required_account_level,
        #[DataCollectionOf(QueueStatusSkillDisparityDTO::class)]
        public array $skill_disparity,
        public int $team_size,
        public bool $tournament,
    ) {}
}
