<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `QueueStatusV1GameRules` schema in openapi.json. Do not edit by hand.
 */
final class QueueStatusGameRulesDTO extends Data
{
    public function __construct(
        public bool $allow_drop_out,
        public bool $allow_lenient_surrender,
        public bool $allow_overtime_draw_vote,
        public bool $assign_random_agents,
        public bool $overtime_win_by_two,
        public bool $overtime_win_by_two_capped,
        public bool $premier_mode,
        public bool $skip_pregame,
    ) {}
}
