<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `QueueStatusV1Maps` schema in openapi.json. Do not edit by hand.
 */
final class QueueStatusMapsDTO extends Data
{
    public function __construct(
        public bool $enabled,
        public QueueStatusMapDTO $map,
    ) {}
}
