<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `QueueStatusV1HighSkill` schema in openapi.json. Do not edit by hand.
 */
final class QueueStatusHighSkillDTO extends Data
{
    public function __construct(
        public int $max_party_size,
        public int $max_tier,
        public int $min_tier,
    ) {}
}
