<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StatusIncidentUpdate` schema in openapi.json. Do not edit by hand.
 */
final class StatusIncidentUpdateDTO extends Data
{
    /**
     * @param  array<int, string>  $publish_locations
     * @param  array<int, StatusIncidentContentDTO>  $translations
     */
    public function __construct(
        public string $author,
        public string $created_at,
        public int $id,
        public bool $publish,
        public array $publish_locations,
        #[DataCollectionOf(StatusIncidentContentDTO::class)]
        public array $translations,
        public string $updated_at,
    ) {}
}
