<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StatusV1Data` schema in openapi.json. Do not edit by hand.
 */
final class StatusDataDTO extends Data
{
    /**
     * @param  array<int, StatusIncidentDTO>  $incidents
     * @param  array<int, StatusIncidentDTO>  $maintenances
     */
    public function __construct(
        #[DataCollectionOf(StatusIncidentDTO::class)]
        public array $incidents,
        #[DataCollectionOf(StatusIncidentDTO::class)]
        public array $maintenances,
    ) {}
}
