<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StatusIncident` schema in openapi.json. Do not edit by hand.
 */
final class StatusIncidentDTO extends Data
{
    /**
     * @param  array<int, string>  $platforms
     * @param  array<int, StatusIncidentContentDTO>  $titles
     * @param  array<int, StatusIncidentUpdateDTO>  $updates
     */
    public function __construct(
        public string $created_at,
        public int $id,
        public string $incident_severity,
        public array $platforms,
        #[DataCollectionOf(StatusIncidentContentDTO::class)]
        public array $titles,
        #[DataCollectionOf(StatusIncidentUpdateDTO::class)]
        public array $updates,
        public ?string $archive_at = null,
        public ?string $maintenance_status = null,
        public ?string $updated_at = null,
    ) {}
}
