<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `StatusIncidentContent` schema in openapi.json. Do not edit by hand.
 */
final class StatusIncidentContentDTO extends Data
{
    public function __construct(
        public string $content,
        public string $locale,
    ) {}
}
