<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Game;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `VersionV1Data` schema in openapi.json. Do not edit by hand.
 */
final class VersionDataDTO extends Data
{
    public function __construct(
        public string $branch,
        public string $build_date,
        public string $build_ver,
        public string $last_checked,
        public string $region,
        public int $version,
        public string $version_for_api,
    ) {}
}
