<?php

namespace Tobiasn\ValorantApi\Requests\Esports;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Esports\EsportsPlayerDTO;
use Tobiasn\ValorantApi\Enums\EsportsPlayerTimespan;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get VLR player (v2)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/esports
 *
 * @generated by bin/generate.php
 */
class GetEsportsPlayerRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    public function __construct(
        private readonly int $playerId,
        private readonly ?EsportsPlayerTimespan $timespan = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v2/esports/vlr/players/'.$this->segment($this->playerId);
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'timespan' => $this->timespan,
        ]);
    }

    public function createDtoFromResponse(Response $response): EsportsPlayerDTO
    {
        return EsportsPlayerDTO::from($this->data($response));
    }
}
