<?php

namespace Tobiasn\ValorantApi\Requests\Esports;

use Illuminate\Support\Collection;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Esports\EsportsTeamMatchDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get VLR team matches (v2)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/esports
 *
 * @generated by bin/generate.php
 */
class GetEsportsTeamMatchesRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    public function __construct(
        private readonly int $teamId,
        private readonly ?int $page = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v2/esports/vlr/teams/'.$this->segment($this->teamId).'/matches';
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'page' => $this->page,
        ]);
    }

    /**
     * @return Collection<int, EsportsTeamMatchDTO>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        return collect($this->data($response))->map(static fn (mixed $item): EsportsTeamMatchDTO => EsportsTeamMatchDTO::from($item));
    }
}
