<?php

namespace Tobiasn\ValorantApi\Requests\Esports;

use Illuminate\Support\Collection;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Esports\EsportsTeamTransactionDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get VLR team transactions (v2)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/esports
 *
 * @generated by bin/generate.php
 */
class GetEsportsTeamTransactionsRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    public function __construct(
        private readonly int $teamId,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v2/esports/vlr/teams/'.$this->segment($this->teamId).'/transactions';
    }

    /**
     * @return Collection<int, EsportsTeamTransactionDTO>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        return collect($this->data($response))->map(static fn (mixed $item): EsportsTeamTransactionDTO => EsportsTeamTransactionDTO::from($item));
    }
}
