<?php

namespace Tobiasn\ValorantApi\Requests\Esports;

use Illuminate\Support\Collection;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Esports\EsportsDataDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get esports schedule (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/esports
 *
 * @generated by bin/generate.php
 */
class GetEsportsScheduleRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    public function __construct(
        private readonly ?string $region = null,
        private readonly ?string $league = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/esports/schedule';
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'region' => $this->region,
            'league' => $this->league,
        ]);
    }

    /**
     * @return Collection<int, EsportsDataDTO>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        return collect($this->data($response))->map(static fn (mixed $item): EsportsDataDTO => EsportsDataDTO::from($item));
    }
}
