<?php

namespace Tobiasn\ValorantApi\Requests\Esports;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Esports\EsportsMatchDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get VLR match details (v2)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/esports
 *
 * @generated by bin/generate.php
 */
class GetEsportsMatchRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    public function __construct(
        private readonly int $matchId,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v2/esports/vlr/matches/'.$this->segment($this->matchId);
    }

    public function createDtoFromResponse(Response $response): EsportsMatchDTO
    {
        return EsportsMatchDTO::from($this->data($response));
    }
}
