<?php

namespace Tobiasn\ValorantApi\Requests\Esports;

use Illuminate\Support\Collection;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Esports\EsportsEventDTO;
use Tobiasn\ValorantApi\Enums\EsportsEventType;
use Tobiasn\ValorantApi\Enums\EsportsRegion;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get VLR esports events (v2)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/esports
 *
 * @generated by bin/generate.php
 */
class GetEsportsEventsRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    public function __construct(
        private readonly ?EsportsRegion $region = null,
        private readonly ?EsportsEventType $type = null,
        private readonly ?int $page = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v2/esports/vlr/events';
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'region' => $this->region,
            'type' => $this->type,
            'page' => $this->page,
        ]);
    }

    /**
     * @return Collection<int, EsportsEventDTO>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        return collect($this->data($response))->map(static fn (mixed $item): EsportsEventDTO => EsportsEventDTO::from($item));
    }
}
