<?php

namespace Tobiasn\ValorantApi\Requests\Esports;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Esports\EsportsTeamDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get VLR team (v2)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/esports
 *
 * @generated by bin/generate.php
 */
class GetEsportsTeamRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    public function __construct(
        private readonly int $teamId,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v2/esports/vlr/teams/'.$this->segment($this->teamId);
    }

    public function createDtoFromResponse(Response $response): EsportsTeamDTO
    {
        return EsportsTeamDTO::from($this->data($response));
    }
}
