<?php

namespace Tobiasn\ValorantApi\Enums;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2Region` schema in openapi.json. Do not edit by hand.
 */
enum EsportsRegion: string
{
    case NorthAmerica = 'north_america';
    case Europe = 'europe';
    case Brazil = 'brazil';
    case AsiaPacific = 'asia_pacific';
    case Korea = 'korea';
    case Japan = 'japan';
    case LatinAmerica = 'latin_america';
    case Oceania = 'oceania';
    case Mena = 'mena';
    case Gc = 'gc';
    case Collegiate = 'collegiate';
}
