<?php

namespace Tobiasn\ValorantApi\Enums;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2EventType` schema in openapi.json. Do not edit by hand.
 */
enum EsportsEventType: string
{
    case Completed = 'completed';
    case Upcoming = 'upcoming';
}
