<?php

namespace Tobiasn\ValorantApi\Enums;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2PlayerTimespan` schema in openapi.json. Do not edit by hand.
 */
enum EsportsPlayerTimespan: string
{
    case Days30 = '30d';
    case Days60 = '60d';
    case Days90 = '90d';
    case All = 'all';
}
