<?php

namespace Tobiasn\ValorantApi\Enums;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2EventStatus` schema in openapi.json. Do not edit by hand.
 */
enum EsportsEventStatus: string
{
    case Completed = 'completed';
    case Ongoing = 'ongoing';
    case Upcoming = 'upcoming';
    case Unknown = 'unknown';
}
