<?php

namespace Tobiasn\ValorantApi\Enums;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremiumWebhookEvent` schema in openapi.json. Do not edit by hand.
 */
enum PremiumWebhookEvent: string
{
    case Match = 'MATCH';
    case Mmr = 'MMR';
}
