<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Raw;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `RawV1Payload` schema in openapi.json. Do not edit by hand.
 */
final class RawPayloadDTO extends Data
{
    /**
     * @param  string|array<int, string>  $value
     */
    public function __construct(
        public string $region,
        public string $type,
        public string|array $value,
        public ?string $platform = null,
        public ?string $queries = null,
    ) {}
}
