<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Account;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `AccountV2Data` schema in openapi.json. Do not edit by hand.
 */
final class AccountDataDTO extends Data
{
    /**
     * @param  array<int, string>  $platforms
     */
    public function __construct(
        public int $account_level,
        public string $card,
        public string $name,
        public array $platforms,
        public string $puuid,
        public string $region,
        public string $tag,
        public string $title,
        public string $updated_at,
    ) {}
}
