<?php

namespace Tobiasn\ValorantApi\Requests\Website;

use Illuminate\Support\Collection;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Website\WebsiteDataDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get website content (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/website
 *
 * @generated by bin/generate.php
 */
class GetWebsiteArticlesRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  string  $countryCode  Country code (e.g., en-us, de-de)
     * @param  string|null  $category  Category filter (optional)
     */
    public function __construct(
        private readonly string $countryCode,
        private readonly ?string $category = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/website/'.$this->segment($this->countryCode);
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'category' => $this->category,
        ]);
    }

    /**
     * @return Collection<int, WebsiteDataDTO>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        return collect($this->data($response))->map(static fn (mixed $item): WebsiteDataDTO => WebsiteDataDTO::from($item));
    }
}
