<?php

namespace Tobiasn\ValorantApi\Requests\Website;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Website\WebsiteByIdDataDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get website entry by ID (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/website
 *
 * @generated by bin/generate.php
 */
class GetWebsiteArticleRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  string  $countryCode  Country code (e.g., en-us, de-de)
     * @param  string  $dbId  Database ID of the website entry
     */
    public function __construct(
        private readonly string $countryCode,
        private readonly string $dbId,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/website/'.$this->segment($this->countryCode).'/'.$this->segment($this->dbId);
    }

    public function createDtoFromResponse(Response $response): WebsiteByIdDataDTO
    {
        return WebsiteByIdDataDTO::from($this->data($response));
    }
}
