<?php

namespace Tobiasn\ValorantApi\Requests\Raw;

use Saloon\Contracts\Body\HasBody;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Traits\Body\HasJsonBody;
use Tobiasn\ValorantApi\DataTransferObjects\Raw\RawPayloadDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\SendsJsonPayload;

/**
 * Get raw Riot API data (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/raw
 *
 * @generated by bin/generate.php
 */
class GetRawDataRequest extends Request implements HasBody
{
    use HasJsonBody;
    use NormalisesParameters;
    use SendsJsonPayload;

    protected Method $method = Method::POST;

    /**
     * @param  RawPayloadDTO  $payload  The request body sent as JSON.
     */
    public function __construct(
        private readonly RawPayloadDTO $payload,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/raw';
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultBody(): array
    {
        return $this->payloadToBody($this->payload);
    }
}
