<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Website;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `WebsiteV1Data` schema in openapi.json. Do not edit by hand.
 */
final class WebsiteDataDTO extends Data
{
    public function __construct(
        public string $category,
        public string $date,
        public string $id,
        public string $title,
        public string $url,
        public ?string $banner_url = null,
        public ?string $description = null,
        public ?string $external_link = null,
    ) {}
}
