<?php

namespace Tobiasn\ValorantApi\Requests\Leaderboard;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Leaderboard\LeaderboardDataDTO;
use Tobiasn\ValorantApi\Enums\Platform;
use Tobiasn\ValorantApi\Enums\Region;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get leaderboard (v3)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/leaderboard
 *
 * @generated by bin/generate.php
 */
class GetLeaderboardRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  Region|string  $affinity  Region/affinity (e.g., na, eu, ap, kr)
     * @param  Platform|string  $platform  Platform (pc, console)
     * @param  string|null  $season  Season ID (optional)
     * @param  int|null  $size  Number of results per page (optional)
     * @param  int|null  $page  Page number (optional)
     * @param  string|null  $name  Player name to search for (optional)
     * @param  string|null  $tag  Player tag to search for (optional)
     */
    public function __construct(
        private readonly Region|string $affinity,
        private readonly Platform|string $platform,
        private readonly ?string $season = null,
        private readonly ?int $size = null,
        private readonly ?int $page = null,
        private readonly ?string $name = null,
        private readonly ?string $tag = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v3/leaderboard/'.$this->segment($this->affinity).'/'.$this->segment($this->platform);
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'season' => $this->season,
            'size' => $this->size,
            'page' => $this->page,
            'name' => $this->name,
            'tag' => $this->tag,
        ]);
    }

    public function createDtoFromResponse(Response $response): LeaderboardDataDTO
    {
        return LeaderboardDataDTO::from($this->data($response));
    }
}
