<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Shared;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `Pagination` schema in openapi.json. Do not edit by hand.
 */
final class PaginationDTO extends Data
{
    public function __construct(
        public int $after,
        public int $before,
        public int $returned,
        public int $total,
    ) {}
}
