<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Shared;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `SeasonIdShortCombo` schema in openapi.json. Do not edit by hand.
 */
final class SeasonIdShortComboDTO extends Data
{
    public function __construct(
        public string $id,
        public string $short,
    ) {}
}
