<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Shared;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `TierIdNameCombo` schema in openapi.json. Do not edit by hand.
 */
final class TierIdNameComboDTO extends Data
{
    public function __construct(
        public int $id,
        public string $name,
    ) {}
}
