<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Errors;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `APIError` schema in openapi.json. Do not edit by hand.
 */
final class APIErrorDTO extends Data
{
    public function __construct(
        public int $code,
        public string $message,
        public int $status,
        public mixed $details = null,
    ) {}
}
