<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Errors;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `SendError` schema in openapi.json. Do not edit by hand.
 */
final class SendErrorDTO extends Data
{
    /**
     * @param  array<int, APIErrorDTO>  $errors
     */
    public function __construct(
        #[DataCollectionOf(APIErrorDTO::class)]
        public array $errors,
    ) {}
}
