<?php

namespace Tobiasn\ValorantApi\Requests\Store;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Store\StoreOffersDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get store offers
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/store
 *
 * @generated by bin/generate.php
 */
class GetStoreOffersRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  string  $version  API version (v1, v2)
     */
    public function __construct(
        private readonly string $version = 'v1',
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/'.$this->segment($this->version).'/store-offers';
    }

    public function createDtoFromResponse(Response $response): StoreOffersDTO
    {
        return StoreOffersDTO::from($this->data($response));
    }
}
