<?php

namespace Tobiasn\ValorantApi\Requests\Store;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Store\StoreFeaturedDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;

/**
 * Get featured store items
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/store
 *
 * @generated by bin/generate.php
 */
class GetStoreFeaturedRequest extends Request
{
    use NormalisesParameters;

    protected Method $method = Method::GET;

    /**
     * @param  string  $version  API version (v1, v2)
     */
    public function __construct(
        private readonly string $version = 'v1',
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/'.$this->segment($this->version).'/store-featured';
    }

    public function createDtoFromResponse(Response $response): StoreFeaturedDTO
    {
        return StoreFeaturedDTO::from($response->json());
    }
}
