<?php

namespace Tobiasn\ValorantApi\Requests\Content;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Content\ContentDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get content (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/content
 *
 * @generated by bin/generate.php
 */
class GetContentRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  string|null  $locale  Locale code (e.g., en-US, de-DE) - optional
     */
    public function __construct(
        private readonly ?string $locale = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/content';
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'locale' => $this->locale,
        ]);
    }

    public function createDtoFromResponse(Response $response): ContentDTO
    {
        return ContentDTO::from($this->data($response));
    }
}
