<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premium;

use Spatie\LaravelData\Attributes\WithCast;
use Spatie\LaravelData\Data;
use Tobiasn\ValorantApi\Casts\EnumArrayCast;
use Tobiasn\ValorantApi\Enums\PremiumWebhookEvent;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremiumWebhookUserResponse` schema in openapi.json. Do not edit by hand.
 */
final class PremiumWebhookUserResponseDTO extends Data
{
    /**
     * @param  array<int, PremiumWebhookEvent>  $events
     */
    public function __construct(
        public int $created_at,
        public bool $enabled,
        #[WithCast(EnumArrayCast::class, PremiumWebhookEvent::class)]
        public array $events,
        public string $id,
        public string $puuid,
        public string $region,
        public int $updated_at,
        public ?int $last_checked_at = null,
        public ?string $last_match = null,
        public ?int $last_mmr = null,
    ) {}
}
