<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premium;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremiumWebhookUserMutationData` schema in openapi.json. Do not edit by hand.
 */
final class PremiumWebhookUserMutationDataDTO extends Data
{
    public function __construct(
        public bool $success,
        public PremiumWebhookUserResponseDTO $user,
    ) {}
}
