<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premium;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremiumWebhookDeleteData` schema in openapi.json. Do not edit by hand.
 */
final class PremiumWebhookDeleteDataDTO extends Data
{
    public function __construct(
        public bool $deleted,
    ) {}
}
