<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Premium;

use Spatie\LaravelData\Attributes\WithCast;
use Spatie\LaravelData\Data;
use Tobiasn\ValorantApi\Casts\EnumArrayCast;
use Tobiasn\ValorantApi\Enums\PremiumWebhookEvent;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `PremiumWebhookUserUpdateRequest` schema in openapi.json. Do not edit by hand.
 */
final class PremiumWebhookUserUpdateRequestDTO extends Data
{
    /**
     * @param  array<int, PremiumWebhookEvent>|null  $events
     */
    public function __construct(
        #[WithCast(EnumArrayCast::class, PremiumWebhookEvent::class)]
        public ?array $events = null,
    ) {}
}
