<?php

namespace Tobiasn\ValorantApi\Requests\Game;

use Illuminate\Support\Collection;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Game\QueueStatusDataDTO;
use Tobiasn\ValorantApi\Enums\Region;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get queue status (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/status
 *
 * @generated by bin/generate.php
 */
class GetQueueStatusRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  Region|string  $affinity  Region/affinity (e.g., na, eu, ap, kr)
     */
    public function __construct(
        private readonly Region|string $affinity,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/queue-status/'.$this->segment($this->affinity);
    }

    /**
     * @return Collection<int, QueueStatusDataDTO>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        return collect($this->data($response))->map(static fn (mixed $item): QueueStatusDataDTO => QueueStatusDataDTO::from($item));
    }
}
