<?php

namespace Tobiasn\ValorantApi\Requests\Game;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Game\VersionDataDTO;
use Tobiasn\ValorantApi\Enums\Region;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get game version (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/status
 *
 * @generated by bin/generate.php
 */
class GetVersionRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  Region|string  $affinity  Region/affinity (e.g., na, eu, ap, kr)
     */
    public function __construct(
        private readonly Region|string $affinity,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/version/'.$this->segment($this->affinity);
    }

    public function createDtoFromResponse(Response $response): VersionDataDTO
    {
        return VersionDataDTO::from($this->data($response));
    }
}
