<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Content;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `ContentV1` schema in openapi.json. Do not edit by hand.
 */
final class ContentDTO extends Data
{
    /**
     * @param  array<int, ContentItemDTO>  $acts
     * @param  array<int, ContentItemDTO>  $ceremonies
     * @param  array<int, ContentItemDTO>  $characters
     * @param  array<int, ContentItemDTO>  $charmLevels
     * @param  array<int, ContentItemDTO>  $charms
     * @param  array<int, ContentItemDTO>  $chromas
     * @param  array<int, ContentItemDTO>  $equips
     * @param  array<int, ContentItemDTO>  $gameModes
     * @param  array<int, ContentItemDTO>  $maps
     * @param  array<int, ContentItemDTO>  $playerCards
     * @param  array<int, ContentItemDTO>  $playerTitles
     * @param  array<int, ContentItemDTO>  $skinLevels
     * @param  array<int, ContentItemDTO>  $skins
     * @param  array<int, ContentItemDTO>  $sprayLevels
     * @param  array<int, ContentItemDTO>  $sprays
     */
    public function __construct(
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $acts,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $ceremonies,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $characters,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $charmLevels,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $charms,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $chromas,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $equips,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $gameModes,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $maps,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $playerCards,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $playerTitles,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $skinLevels,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $skins,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $sprayLevels,
        #[DataCollectionOf(ContentItemDTO::class)]
        public array $sprays,
        public string $version,
    ) {}
}
