<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Content;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `ContentItem` schema in openapi.json. Do not edit by hand.
 */
final class ContentItemDTO extends Data
{
    /**
     * @param  array<string, string>|null  $localizedNames
     */
    public function __construct(
        public string $assetName,
        public string $name,
        public ?string $id = null,
        public ?array $localizedNames = null,
    ) {}
}
