<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Leaderboard;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `LeaderboardV3DataPlayer` schema in openapi.json. Do not edit by hand.
 */
final class LeaderboardDataPlayerDTO extends Data
{
    public function __construct(
        public string $card,
        public bool $is_anonymized,
        public bool $is_banned,
        public int $leaderboard_rank,
        public string $name,
        public int $rr,
        public string $tag,
        public int $tier,
        public string $title,
        public string $updated_at,
        public int $wins,
        public ?string $puuid = null,
    ) {}
}
