<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Leaderboard;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `LeaderboardV3DataThreshold` schema in openapi.json. Do not edit by hand.
 */
final class LeaderboardDataThresholdDTO extends Data
{
    public function __construct(
        public int $start_index,
        public int $threshold,
        public LeaderboardDataThresholdTierDTO $tier,
    ) {}
}
