<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Leaderboard;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `LeaderboardV3DataThresholdTier` schema in openapi.json. Do not edit by hand.
 */
final class LeaderboardDataThresholdTierDTO extends Data
{
    public function __construct(
        public int $id,
        public string $name,
    ) {}
}
