<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Leaderboard;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `LeaderboardV3Data` schema in openapi.json. Do not edit by hand.
 */
final class LeaderboardDataDTO extends Data
{
    /**
     * @param  array<int, LeaderboardDataPlayerDTO>  $players
     * @param  array<int, LeaderboardDataThresholdDTO>  $thresholds
     */
    public function __construct(
        #[DataCollectionOf(LeaderboardDataPlayerDTO::class)]
        public array $players,
        #[DataCollectionOf(LeaderboardDataThresholdDTO::class)]
        public array $thresholds,
        public string $updated_at,
    ) {}
}
