<?php

namespace Tobiasn\ValorantApi\Requests\Premier;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Premier\PremierTeamResponseDataDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get Premier team by ID (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/premier
 *
 * @generated by bin/generate.php
 */
class GetPremierTeamByIdRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  string  $id  Team UUID
     * @param  string|null  $season  Premier season id (optional)
     * @param  string|null  $affinity  Region/affinity for fallback resolution (optional)
     */
    public function __construct(
        private readonly string $id,
        private readonly ?string $season = null,
        private readonly ?string $affinity = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/premier/'.$this->segment($this->id);
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'season' => $this->season,
            'affinity' => $this->affinity,
        ]);
    }

    public function createDtoFromResponse(Response $response): PremierTeamResponseDataDTO
    {
        return PremierTeamResponseDataDTO::from($this->data($response));
    }
}
