<?php

namespace Tobiasn\ValorantApi\Requests\Premier;

use Illuminate\Support\Collection;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Premier\PremierTeamLiteResponseDataDTO;
use Tobiasn\ValorantApi\Enums\Region;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get Premier leaderboard (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/premier
 *
 * @generated by bin/generate.php
 */
class GetPremierLeaderboardRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  Region|string  $affinity  Region/affinity (e.g., na, eu, ap, kr)
     * @param  string|null  $conference  Conference filter (optional)
     * @param  string|null  $division  Division filter (optional)
     * @param  string|null  $season  Premier season id (optional)
     */
    public function __construct(
        private readonly Region|string $affinity,
        private readonly ?string $conference = null,
        private readonly ?string $division = null,
        private readonly ?string $season = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/premier/leaderboard/'.$this->segment($this->affinity);
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'conference' => $this->conference,
            'division' => $this->division,
            'season' => $this->season,
        ]);
    }

    /**
     * @return Collection<int, PremierTeamLiteResponseDataDTO>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        return collect($this->data($response))->map(static fn (mixed $item): PremierTeamLiteResponseDataDTO => PremierTeamLiteResponseDataDTO::from($item));
    }
}
