<?php

namespace Tobiasn\ValorantApi\Requests\Premier;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Premier\PremierTeamHistoryResponseDataDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Get Premier team history by name (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/premier
 *
 * @generated by bin/generate.php
 */
class GetPremierTeamHistoryRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  string  $name  Team name
     * @param  string  $tag  Team tag
     * @param  string|null  $season  Premier season id (optional)
     */
    public function __construct(
        private readonly string $name,
        private readonly string $tag,
        private readonly ?string $season = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/premier/'.$this->segment($this->name).'/'.$this->segment($this->tag).'/history';
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'season' => $this->season,
        ]);
    }

    public function createDtoFromResponse(Response $response): PremierTeamHistoryResponseDataDTO
    {
        return PremierTeamHistoryResponseDataDTO::from($this->data($response));
    }
}
