<?php

namespace Tobiasn\ValorantApi\Requests\Premier;

use Illuminate\Support\Collection;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Tobiasn\ValorantApi\DataTransferObjects\Premier\PremierTeamLiteResponseDataDTO;
use Tobiasn\ValorantApi\Requests\Concerns\NormalisesParameters;
use Tobiasn\ValorantApi\Requests\Concerns\ReadsResponseData;

/**
 * Search Premier teams (v1)
 *
 * @see https://docs.henrikdev.xyz/valorant/api-reference/premier
 *
 * @generated by bin/generate.php
 */
class SearchPremierTeamsRequest extends Request
{
    use NormalisesParameters;
    use ReadsResponseData;

    protected Method $method = Method::GET;

    /**
     * @param  string|null  $name  Team name to search for (optional)
     * @param  string|null  $tag  Team tag to search for (optional)
     * @param  string|null  $id  Team UUID to search for (optional)
     * @param  string|null  $season  Premier season id (optional)
     */
    public function __construct(
        private readonly ?string $name = null,
        private readonly ?string $tag = null,
        private readonly ?string $id = null,
        private readonly ?string $season = null,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/valorant/v1/premier/search';
    }

    /**
     * @return array<string, mixed>
     */
    protected function defaultQuery(): array
    {
        return $this->filterQuery([
            'name' => $this->name,
            'tag' => $this->tag,
            'id' => $this->id,
            'season' => $this->season,
        ]);
    }

    /**
     * @return Collection<int, PremierTeamLiteResponseDataDTO>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        return collect($this->data($response))->map(static fn (mixed $item): PremierTeamLiteResponseDataDTO => PremierTeamLiteResponseDataDTO::from($item));
    }
}
