<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2Match` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchDTO extends Data
{
    /**
     * @param  array<int, EsportsMatchGameDTO>  $games
     * @param  array<int, EsportsHeadToHeadMatchDTO>  $head_to_head
     * @param  array<int, EsportsTeamPastMatchesDTO>  $past_matches
     * @param  array<int, EsportsMatchStreamDTO>  $streams
     * @param  array<int, EsportsMatchHeaderTeamDTO>  $teams
     * @param  array<int, EsportsMatchStreamDTO>  $vods
     */
    public function __construct(
        #[DataCollectionOf(EsportsMatchGameDTO::class)]
        public array $games,
        #[DataCollectionOf(EsportsHeadToHeadMatchDTO::class)]
        public array $head_to_head,
        public EsportsMatchHeaderDTO $metadata,
        #[DataCollectionOf(EsportsTeamPastMatchesDTO::class)]
        public array $past_matches,
        #[DataCollectionOf(EsportsMatchStreamDTO::class)]
        public array $streams,
        #[DataCollectionOf(EsportsMatchHeaderTeamDTO::class)]
        public array $teams,
        #[DataCollectionOf(EsportsMatchStreamDTO::class)]
        public array $vods,
        public ?EsportsMatchEconomyDTO $economy = null,
        public ?EsportsMatchPerformanceDTO $performance = null,
    ) {}
}
