<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2Social` schema in openapi.json. Do not edit by hand.
 */
final class EsportsSocialDTO extends Data
{
    public function __construct(
        public string $platform,
        public string $url,
    ) {}
}
