<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2EventDetail` schema in openapi.json. Do not edit by hand.
 */
final class EsportsEventDetailDTO extends Data
{
    /**
     * @param  array<int, string>  $tags
     * @param  array<int, EsportsMatchTeamDTO>  $teams
     */
    public function __construct(
        public string $event,
        public int $id,
        public string $series,
        public string $slug,
        public array $tags,
        #[DataCollectionOf(EsportsMatchTeamDTO::class)]
        public array $teams,
        public ?string $date = null,
    ) {}
}
