<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2TransactionPlayer` schema in openapi.json. Do not edit by hand.
 */
final class EsportsTransactionPlayerDTO extends Data
{
    public function __construct(
        public string $alias,
        public int $id,
        public string $slug,
        public ?string $country_code = null,
        public ?string $real_name = null,
    ) {}
}
