<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchStream` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchStreamDTO extends Data
{
    public function __construct(
        public string $link,
        public string $name,
    ) {}
}
