<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2Country` schema in openapi.json. Do not edit by hand.
 */
final class EsportsCountryDTO extends Data
{
    public function __construct(
        public string $code,
        public string $name,
    ) {}
}
