<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2Team` schema in openapi.json. Do not edit by hand.
 */
final class EsportsTeamDTO extends Data
{
    /**
     * @param  array<int, EsportsEventPlacementDTO>  $event_placements
     * @param  array<int, EsportsTeamRosterMemberDTO>  $roster
     * @param  array<int, EsportsSocialDTO>  $socials
     */
    public function __construct(
        #[DataCollectionOf(EsportsEventPlacementDTO::class)]
        public array $event_placements,
        public int $id,
        public string $name,
        #[DataCollectionOf(EsportsTeamRosterMemberDTO::class)]
        public array $roster,
        #[DataCollectionOf(EsportsSocialDTO::class)]
        public array $socials,
        public ?EsportsCountryDTO $country = null,
        public ?string $logo = null,
        public ?string $tag = null,
        public ?string $total_winnings = null,
    ) {}
}
