<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV1DataLeague` schema in openapi.json. Do not edit by hand.
 */
final class EsportsDataLeagueDTO extends Data
{
    public function __construct(
        public string $icon,
        public string $identifier,
        public string $name,
        public string $region,
    ) {}
}
