<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2TeamEconomyRoundWon` schema in openapi.json. Do not edit by hand.
 */
final class EsportsTeamEconomyRoundWonDTO extends Data
{
    public function __construct(
        public int $rounds,
        public int $won,
    ) {}
}
