<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchEconomy` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchEconomyDTO extends Data
{
    /**
     * @param  array<int, EsportsTeamEconomyDTO>  $teams
     */
    public function __construct(
        #[DataCollectionOf(EsportsTeamEconomyDTO::class)]
        public array $teams,
    ) {}
}
