<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2Date` schema in openapi.json. Do not edit by hand.
 */
final class EsportsDateDTO extends Data
{
    public function __construct(
        public ?string $end = null,
        public ?string $start = null,
    ) {}
}
