<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchHeader` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchHeaderDTO extends Data
{
    public function __construct(
        public string $date,
        public EsportsMatchEventDTO $event,
        public string $format,
        public string $note,
        public string $patch,
        public string $status,
    ) {}
}
