<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2HeadToHeadEvent` schema in openapi.json. Do not edit by hand.
 */
final class EsportsHeadToHeadEventDTO extends Data
{
    public function __construct(
        public string $icon,
        public string $name,
        public string $series,
    ) {}
}
