<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2Player` schema in openapi.json. Do not edit by hand.
 */
final class EsportsPlayerDTO extends Data
{
    /**
     * @param  array<int, EsportsPlayerAgentStatsDTO>  $agent_stats
     * @param  array<int, EsportsPlayerTeamDTO>  $current_teams
     * @param  array<int, EsportsEventPlacementDTO>  $event_placements
     * @param  array<int, EsportsPlayerTeamDTO>  $past_teams
     * @param  array<int, EsportsSocialDTO>  $socials
     */
    public function __construct(
        #[DataCollectionOf(EsportsPlayerAgentStatsDTO::class)]
        public array $agent_stats,
        #[DataCollectionOf(EsportsPlayerTeamDTO::class)]
        public array $current_teams,
        #[DataCollectionOf(EsportsEventPlacementDTO::class)]
        public array $event_placements,
        public int $id,
        public string $name,
        #[DataCollectionOf(EsportsPlayerTeamDTO::class)]
        public array $past_teams,
        #[DataCollectionOf(EsportsSocialDTO::class)]
        public array $socials,
        public ?string $avatar = null,
        public ?EsportsCountryDTO $country = null,
        public ?string $real_name = null,
        public ?string $total_winnings = null,
    ) {}
}
