<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV1Data` schema in openapi.json. Do not edit by hand.
 */
final class EsportsDataDTO extends Data
{
    public function __construct(
        public string $date,
        public EsportsDataLeagueDTO $league,
        public EsportsDataMatchDTO $match,
        public string $state,
        public EsportsDataTournamentDTO $tournament,
        public string $type,
        public ?string $vod = null,
    ) {}
}
