<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2AgentUsage` schema in openapi.json. Do not edit by hand.
 */
final class EsportsAgentUsageDTO extends Data
{
    public function __construct(
        public int $count,
        public float $percentage,
        public int $rounds,
    ) {}
}
