<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchGame` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchGameDTO extends Data
{
    /**
     * @param  array<int, EsportsMatchGameRoundDTO>  $rounds
     * @param  array<int, EsportsMatchGameTeamDTO>  $teams
     */
    public function __construct(
        public string $map,
        #[DataCollectionOf(EsportsMatchGameRoundDTO::class)]
        public array $rounds,
        #[DataCollectionOf(EsportsMatchGameTeamDTO::class)]
        public array $teams,
        public ?int $duration_in_s = null,
        public ?int $picked_by = null,
    ) {}
}
