<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2HeadToHeadScore` schema in openapi.json. Do not edit by hand.
 */
final class EsportsHeadToHeadScoreDTO extends Data
{
    public function __construct(
        public int $team_1,
        public int $team_2,
        public int $winner_team,
    ) {}
}
