<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2TeamEconomy` schema in openapi.json. Do not edit by hand.
 */
final class EsportsTeamEconomyDTO extends Data
{
    public function __construct(
        public EsportsTeamEconomyRoundWonDTO $eco,
        public EsportsTeamEconomyRoundWonDTO $full_buy,
        public int $pistol_won,
        public EsportsTeamEconomyRoundWonDTO $semi_eco,
        public string $team_name,
    ) {}
}
