<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchGamePlayerStats` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchGamePlayerStatsDTO extends Data
{
    public function __construct(
        public ?int $acs = null,
        public ?float $adr = null,
        public ?int $assists = null,
        public ?int $deaths = null,
        public ?int $first_deaths = null,
        public ?int $first_kills = null,
        public ?int $fk_diff = null,
        public ?float $hs_pct = null,
        public ?float $kast = null,
        public ?int $kd_diff = null,
        public ?int $kills = null,
        public ?float $rating = null,
    ) {}
}
