<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2TeamTransaction` schema in openapi.json. Do not edit by hand.
 */
final class EsportsTeamTransactionDTO extends Data
{
    public function __construct(
        public string $action,
        public EsportsTransactionPlayerDTO $player,
        public string $position,
        public ?string $date = null,
        public ?string $reference_url = null,
    ) {}
}
