<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchGameTeam` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchGameTeamDTO extends Data
{
    /**
     * @param  array<int, EsportsMatchGamePlayerDTO>  $players
     */
    public function __construct(
        public bool $is_winner,
        public string $name,
        #[DataCollectionOf(EsportsMatchGamePlayerDTO::class)]
        public array $players,
        public ?int $score = null,
        public ?int $score_ct = null,
        public ?int $score_t = null,
    ) {}
}
