<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2PlacementEntry` schema in openapi.json. Do not edit by hand.
 */
final class EsportsPlacementEntryDTO extends Data
{
    public function __construct(
        public string $placement,
        public string $stage,
        public ?string $prize = null,
        public ?string $team = null,
    ) {}
}
