<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2TeamMatch` schema in openapi.json. Do not edit by hand.
 */
final class EsportsTeamMatchDTO extends Data
{
    /**
     * @param  array<int, EsportsTeamMatchTeamDTO>  $teams
     * @param  array<int, string>  $vods
     */
    public function __construct(
        public EsportsMatchLeagueDTO $league,
        public EsportsIdSlugDTO $match,
        #[DataCollectionOf(EsportsTeamMatchTeamDTO::class)]
        public array $teams,
        public array $vods,
        public ?string $date = null,
    ) {}
}
