<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchPerformance` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchPerformanceDTO extends Data
{
    /**
     * @param  array<int, EsportsKillMatrixEntryDTO>  $kill_matrix
     * @param  array<int, EsportsPlayerPerformanceDTO>  $player_performances
     */
    public function __construct(
        #[DataCollectionOf(EsportsKillMatrixEntryDTO::class)]
        public array $kill_matrix,
        #[DataCollectionOf(EsportsPlayerPerformanceDTO::class)]
        public array $player_performances,
    ) {}
}
