<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2EventPlacement` schema in openapi.json. Do not edit by hand.
 */
final class EsportsEventPlacementDTO extends Data
{
    /**
     * @param  array<int, EsportsPlacementEntryDTO>  $placements
     */
    public function __construct(
        public EsportsPlacementEventDTO $event,
        #[DataCollectionOf(EsportsPlacementEntryDTO::class)]
        public array $placements,
        public string $year,
    ) {}
}
