<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2TeamPastMatches` schema in openapi.json. Do not edit by hand.
 */
final class EsportsTeamPastMatchesDTO extends Data
{
    /**
     * @param  array<int, EsportsPastMatchDTO>  $matches
     */
    public function __construct(
        #[DataCollectionOf(EsportsPastMatchDTO::class)]
        public array $matches,
        public int $team,
    ) {}
}
