<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2PastMatch` schema in openapi.json. Do not edit by hand.
 */
final class EsportsPastMatchDTO extends Data
{
    public function __construct(
        public string $date,
        public bool $is_win,
        public EsportsIdSlugDTO $match,
        public EsportsPastMatchOpponentDTO $opponent,
        public EsportsPastMatchScoreDTO $score,
    ) {}
}
