<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV1DataMatchTeams` schema in openapi.json. Do not edit by hand.
 */
final class EsportsDataMatchTeamsDTO extends Data
{
    public function __construct(
        public string $code,
        public int $game_wins,
        public bool $has_won,
        public string $icon,
        public string $name,
        public EsportsDataMatchTeamsRecordDTO $record,
    ) {}
}
