<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchLeague` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchLeagueDTO extends Data
{
    public function __construct(
        public string $icon,
        public string $name,
        public string $series,
    ) {}
}
