<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2PlayerPerformanceMultiKills` schema in openapi.json. Do not edit by hand.
 */
final class EsportsPlayerPerformanceMultiKillsDTO extends Data
{
    public function __construct(
        #[MapInputName('2k')]
        public int $multi_kill_2k,
        #[MapInputName('3k')]
        public int $multi_kill_3k,
        #[MapInputName('4k')]
        public int $multi_kill_4k,
        #[MapInputName('5k')]
        public int $multi_kill_5k,
    ) {}
}
