<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2KillMatrixEntry` schema in openapi.json. Do not edit by hand.
 */
final class EsportsKillMatrixEntryDTO extends Data
{
    public function __construct(
        public int $deaths,
        public int $killer,
        public int $kills,
        public int $victim,
    ) {}
}
