<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchGameRound` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchGameRoundDTO extends Data
{
    public function __construct(
        public int $round,
        public string $winning_site,
        public int $winning_team,
    ) {}
}
