<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchTeam` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchTeamDTO extends Data
{
    public function __construct(
        public bool $is_winner,
        public string $name,
        public ?int $score = null,
    ) {}
}
