<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV1DataMatchGameType` schema in openapi.json. Do not edit by hand.
 */
final class EsportsDataMatchGameTypeDTO extends Data
{
    public function __construct(
        public ?int $count = null,
        public ?string $type = null,
    ) {}
}
