<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2PlayerPerformanceClutches` schema in openapi.json. Do not edit by hand.
 */
final class EsportsPlayerPerformanceClutchesDTO extends Data
{
    public function __construct(
        #[MapInputName('1v1')]
        public int $clutch_1v1,
        #[MapInputName('1v2')]
        public int $clutch_1v2,
        #[MapInputName('1v3')]
        public int $clutch_1v3,
        #[MapInputName('1v4')]
        public int $clutch_1v4,
        #[MapInputName('1v5')]
        public int $clutch_1v5,
    ) {}
}
