<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2PlayerAgentStats` schema in openapi.json. Do not edit by hand.
 */
final class EsportsPlayerAgentStatsDTO extends Data
{
    public function __construct(
        public string $agent,
        public EsportsAgentPerformanceStatsDTO $stats,
        public EsportsAgentUsageDTO $usage,
    ) {}
}
