<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2TeamMatchTeam` schema in openapi.json. Do not edit by hand.
 */
final class EsportsTeamMatchTeamDTO extends Data
{
    public function __construct(
        public string $logo,
        public string $name,
        public string $tag,
        public ?int $score = null,
    ) {}
}
