<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2HeadToHeadMatch` schema in openapi.json. Do not edit by hand.
 */
final class EsportsHeadToHeadMatchDTO extends Data
{
    public function __construct(
        public string $date,
        public EsportsHeadToHeadEventDTO $event,
        public EsportsIdSlugDTO $match,
        public EsportsHeadToHeadScoreDTO $score,
    ) {}
}
