<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchGamePlayer` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchGamePlayerDTO extends Data
{
    public function __construct(
        public string $agent,
        public EsportsMatchPlayerDTO $player,
        public EsportsMatchGamePlayerStatsDTO $stats,
    ) {}
}
