<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV1DataMatch` schema in openapi.json. Do not edit by hand.
 */
final class EsportsDataMatchDTO extends Data
{
    /**
     * @param  array<int, EsportsDataMatchTeamsDTO>  $teams
     */
    public function __construct(
        public EsportsDataMatchGameTypeDTO $game_type,
        #[DataCollectionOf(EsportsDataMatchTeamsDTO::class)]
        public array $teams,
        public ?string $id = null,
    ) {}
}
