<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2AgentPerformanceStats` schema in openapi.json. Do not edit by hand.
 */
final class EsportsAgentPerformanceStatsDTO extends Data
{
    public function __construct(
        public float $acs,
        public float $adr,
        public float $apr,
        public int $assists,
        public int $deaths,
        public float $fdpr,
        public int $first_deaths,
        public int $first_kills,
        public float $fkpr,
        public float $kast,
        public float $kd,
        public int $kills,
        public float $kpr,
        public float $rating,
    ) {}
}
