<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchHeaderTeam` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchHeaderTeamDTO extends Data
{
    public function __construct(
        public string $icon,
        public int $id,
        public string $name,
        public string $slug,
        public string $url,
        public ?int $score = null,
    ) {}
}
