<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2PastMatchScore` schema in openapi.json. Do not edit by hand.
 */
final class EsportsPastMatchScoreDTO extends Data
{
    public function __construct(
        public int $against,
        public int $for,
    ) {}
}
