<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV1DataMatchTeamsRecord` schema in openapi.json. Do not edit by hand.
 */
final class EsportsDataMatchTeamsRecordDTO extends Data
{
    public function __construct(
        public int $losses,
        public int $wins,
    ) {}
}
