<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2MatchEvent` schema in openapi.json. Do not edit by hand.
 */
final class EsportsMatchEventDTO extends Data
{
    public function __construct(
        public string $icon,
        public int $id,
        public string $series,
        public string $slug,
        public string $title,
    ) {}
}
