<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2PlayerPerformance` schema in openapi.json. Do not edit by hand.
 */
final class EsportsPlayerPerformanceDTO extends Data
{
    public function __construct(
        public EsportsPlayerPerformanceClutchesDTO $clutches,
        public int $defuses,
        public int $econ_rating,
        public EsportsPlayerPerformanceMultiKillsDTO $multi_kills,
        public int $plants,
        public EsportsPlayerPerformancePlayerDTO $player,
    ) {}
}
