<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2TeamRosterMember` schema in openapi.json. Do not edit by hand.
 */
final class EsportsTeamRosterMemberDTO extends Data
{
    public function __construct(
        public string $alias,
        public int $id,
        public bool $is_captain,
        public string $role,
        public ?string $avatar = null,
        public ?string $country_code = null,
        public ?string $real_name = null,
    ) {}
}
