<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2PlayerPerformancePlayer` schema in openapi.json. Do not edit by hand.
 */
final class EsportsPlayerPerformancePlayerDTO extends Data
{
    public function __construct(
        public int $id,
        public string $name,
    ) {}
}
