<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;
use Tobiasn\ValorantApi\Enums\EsportsEventStatus;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV2Event` schema in openapi.json. Do not edit by hand.
 */
final class EsportsEventDTO extends Data
{
    public function __construct(
        public EsportsDateDTO $dates,
        public string $icon,
        public int $id,
        public string $price,
        public string $region,
        public string $slug,
        public EsportsEventStatus $status,
        public string $title,
    ) {}
}
