<?php

namespace Tobiasn\ValorantApi\DataTransferObjects\Esports;

use Spatie\LaravelData\Data;

/**
 * @generated by bin/generate.php
 *
 * Generated from the `EsportsV1DataTournament` schema in openapi.json. Do not edit by hand.
 */
final class EsportsDataTournamentDTO extends Data
{
    public function __construct(
        public string $name,
        public string $season,
    ) {}
}
